// <auto-generated />
using System;
using GeoEspectro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoEspectro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoEspectro.Models.Artigos", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Data")
                    .HasColumnType("datetime2");

                b.Property<string>("Texto")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.HasKey("Id");

                b.HasIndex("AutorFK");

                b.ToTable("Artigos");
            });

            modelBuilder.Entity("GeoEspectro.Models.ArtigosCategoria", b =>
            {
                b.Property<int>("ArtigosId").HasColumnType("int");
                b.Property<int>("CategoriaId").HasColumnType("int");

                b.HasKey("ArtigosId", "CategoriaId");
                b.HasIndex("CategoriaId");
                b.ToTable("ArtigosCategoria");
            });

            modelBuilder.Entity("GeoEspectro.Models.Categorias", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Categoria").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Categorias");
            });

            modelBuilder.Entity("GeoEspectro.Models.Detalhes", b =>
            {
                b.Property<int>("RecursoFK").HasColumnType("int");
                b.Property<int>("ArtigoFK").HasColumnType("int");
                b.Property<bool>("Principal").HasColumnType("bit");

                b.HasKey("RecursoFK", "ArtigoFK");
                b.HasIndex("ArtigoFK");
                b.ToTable("Detalhes");
            });

            modelBuilder.Entity("GeoEspectro.Models.Gostos", b =>
            {
                b.Property<int>("UtilizadorFk").HasColumnType("int");
                b.Property<int>("ArtigoFK").HasColumnType("int");
                b.Property<DateTime>("Data").HasColumnType("datetime2");

                b.HasKey("UtilizadorFk", "ArtigoFK");
                b.HasIndex("ArtigoFK");
                b.ToTable("Gostos");
            });

            modelBuilder.Entity("GeoEspectro.Models.Recursos", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("Data").HasColumnType("datetime2");
                b.Property<string>("Ficheiro").HasColumnType("nvarchar(max)");
                b.Property<string>("Local").HasColumnType("nvarchar(max)");
                b.Property<string>("Nome").HasColumnType("nvarchar(max)");
                b.Property<string>("Observacao").HasColumnType("nvarchar(max)");
                b.Property<string>("Tipo").HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("AutorFK");
                b.ToTable("Recursos");
            });

            modelBuilder.Entity("GeoEspectro.Models.Utilizadores", b =>
            {
                b.Property<int>("ID").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<string>("CodPostal").HasColumnType("nvarchar(max)");
                b.Property<string>("Morada").HasColumnType("nvarchar(max)");
                b.Property<string>("NIF").HasColumnType("nvarchar(max)");
                b.Property<string>("Nome").HasColumnType("nvarchar(max)");
                b.Property<string>("Pais").HasColumnType("nvarchar(max)");
                b.Property<string>("Telemovel").HasColumnType("nvarchar(max)");

                b.HasKey("ID");
                b.ToTable("Utilizadores");
            });

            modelBuilder.Entity("GeoEspectro.Models.Artigos", b =>
            {
                b.HasOne("GeoEspectro.Models.Utilizadores", "Autor")
                    .WithMany("ListaArtigos")
                    .HasForeignKey("AutorFK")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Autor");
            });

            modelBuilder.Entity("GeoEspectro.Models.ArtigosCategoria", b =>
            {
                b.HasOne("GeoEspectro.Models.Artigos", "Artigos")
                    .WithMany("ListaCategorias")
                    .HasForeignKey("ArtigosId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GeoEspectro.Models.Categorias", "Categoria")
                    .WithMany("ListaArtigos")
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Artigos");
                b.Navigation("Categoria");
            });

            modelBuilder.Entity("GeoEspectro.Models.Detalhes", b =>
            {
                b.HasOne("GeoEspectro.Models.Artigos", "Artigo")
                    .WithMany("ListaRecursos")
                    .HasForeignKey("ArtigoFK")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GeoEspectro.Models.Recursos", "Recurso")
                    .WithMany("ListaArtigos")
                    .HasForeignKey("RecursoFK")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Artigo");
                b.Navigation("Recurso");
            });

            modelBuilder.Entity("GeoEspectro.Models.Gostos", b =>
            {
                b.HasOne("GeoEspectro.Models.Artigos", "Artigo")
                    .WithMany("ListaGostos")
                    .HasForeignKey("ArtigoFK")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GeoEspectro.Models.Utilizadores", "Utilizador")
                    .WithMany("ListaGostos")
                    .HasForeignKey("UtilizadorFk")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Artigo");
                b.Navigation("Utilizador");
            });

            modelBuilder.Entity("GeoEspectro.Models.Recursos", b =>
                {
});

            modelBuilder.Entity("GeoEspectro.Models.Artigos", b =>
            {
                b.Navigation("ListaCategorias");
                b.Navigation("ListaGostos");
                b.Navigation("ListaRecursos");
            });

            modelBuilder.Entity("GeoEspectro.Models.Categorias", b =>
            {
                b.Navigation("ListaArtigos");
            });

            modelBuilder.Entity("GeoEspectro.Models.Recursos", b =>
            {
                b.Navigation("ListaArtigos");
            });

            modelBuilder.Entity("GeoEspectro.Models.Utilizadores", b =>
            {
                b.Navigation("ListaArtigos");
                b.Navigation("ListaGostos");
                b.Navigation("ListaRecursos");
            });
#pragma warning restore 612, 618
        }
    }
}